import { chromium } from 'playwright';
import { createServer } from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import assert from 'node:assert/strict';
import { kstToday, shiftCalendarMonths } from '../public/assets/catalog-view.mjs';

const root=path.resolve('public'), out=await fs.mkdtemp(path.join(os.tmpdir(),'shoes-ui-'));
const mime={'.html':'text/html','.css':'text/css','.mjs':'text/javascript','.json':'application/json'};
const server=createServer(async(req,res)=>{try{const requestPath=decodeURIComponent(new URL(req.url,'http://local').pathname),filename=path.resolve(root,'.'+(requestPath==='/'?'/index.html':requestPath));if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return;}const data=await fs.readFile(filename);res.writeHead(200,{'Content-Type':mime[path.extname(filename)]||'application/octet-stream'}).end(data);}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}/`, today=kstToday();
const svg='<svg xmlns="http://www.w3.org/2000/svg" width="400" height="300"><rect width="400" height="300" fill="#f6f7f9"/><path d="M72 188 L103 132 L158 151 L200 179 L304 192 Q330 207 313 217 L81 217 Q63 213 72 188" fill="#fefefe" stroke="#a7b6c9" stroke-width="4"/><path d="M107 177 L168 186 M124 162 L180 180" stroke="#8ca1bc" stroke-width="7"/></svg>';
const fixture={schemaVersion:1,publishedAt:new Date().toISOString(),periodStart:shiftCalendarMonths(today,-3),brands:[{id:'nike',name:'Nike',group:'outdoor',mandatory:true,policy:'mandatory'}],sourceStatus:{lastSuccessfulCollectionAt:new Date().toISOString(),unavailableBrands:[],notes:[]},products:Array.from({length:48},(_,i)=>({id:`p${i}`,brand:'Nike',name:`테스트 Runner ${String(i).padStart(2,'0')}`,category:'sneaker',productType:'스니커즈',fit:i%2?['MLB']:['MLB','DISCOVERY'],fitReasons:['경량 메시와 레트로 실루엣'],releaseDate:today,releaseStatus:'released',dateEvidence:{url:'https://example.org/release',region:'US',verifiedAt:new Date().toISOString()},url:`https://example.org/product/${i}`,image:'https://example.org/image.svg',style:`STYLE-${i}`,colorway:'White / Blue',colors:[{name:'White',hex:'#FFFFFF'}],material:'Mesh',priceLabel:'$120',popularity:{magazine:i===0,sns:false},sourceSignals:i===0?[{type:'magazine',title:'상품 소개',url:'https://example.org/editorial',publishedAt:today,checkedAt:today}]:[],archiveGroup:'outdoor'})),keywords:[{id:'retro',label:'레트로',rank:1,sourceTypes:['magazine'],productIds:['p0','p1'],productCount:2,previousProductCount:1,growth:1}]};
fixture.products.push({...fixture.products[0],id:'expired',releaseDate:'2020-01-01'});
fixture.products.push({...fixture.products[0],id:'upcoming',name:'Upcoming Runner',releaseDate:shiftCalendarMonths(today,1),releaseStatus:'upcoming'});
fixture.products.push({...fixture.products[0],id:'unknown',name:'Unknown date runner',releaseDate:''});
fixture.keywords=Array.from({length:21},(_,i)=>({id:`theme-${i}`,label:i===0?'Retro Runners':i===1?'Trail Inspired':`Theme ${String(i+1).padStart(2,'0')}`,aliases:i===1?['트레일']:[],rank:i===0?1:null,rankingStatus:i===0?'ranked':'awaiting-evidence',sourceTypes:i===0?['magazine']:[],productIds:i===0?fixture.products.map(p=>p.id):i===1?['p0','p1']:[],evidenceProductIds:i===0?['p0']:[],productCount:i===0?1:0,matchedProductCount:i===0?49:i===1?2:0,previousProductCount:0,growth:i===0?1:0}));
fixture.products[0].sourceSignals[0].publisherName='Verified Editorial';fixture.products[0].sourceSignals[0].publisherId='verified-editorial';
fixture.products[0].sourceSignals.push({type:'ecommerce',title:'Weekly BEST',url:'https://ranking.example/best',publisherName:'Verified Commerce',rank:4,rankingCategory:'스니커즈',rankingPeriod:'최근 1주',rankingDefinition:'BEST 목록의 표시 순위',checkedAt:today});
fixture.sourceDirectory={magazine:{configured:[{id:'verified-editorial',name:'Verified Editorial',url:'https://example.org/'},{id:'planned-editorial',name:'Planned Editorial',url:'https://planned.example/'}],observed:[{id:'verified-editorial',name:'Verified Editorial',url:'https://example.org/',itemCount:1}]},newsletter:{configured:[{id:'planned-newsletter',name:'Planned Newsletter',url:'https://newsletter.example/'}],observed:[]},sns:{configured:[],observed:[]},ecommerce:{configured:[],observed:[]}};
const errors=[],requests=[];let browser;
try{
  browser=await chromium.launch({headless:true,channel:process.env.UI_BROWSER_CHANNEL || (process.platform==='win32'?'chrome':undefined)});
  const context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true});
  await context.route('**/data/catalog.json',r=>r.fulfill({contentType:'application/json',body:JSON.stringify(fixture)}));
  await context.route('https://example.org/image.svg',r=>r.fulfill({contentType:'image/svg+xml',body:svg}));
  await context.route('https://fonts.googleapis.com/**',r=>r.fulfill({contentType:'text/css',body:''}));
  const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push({url:request.url(),method:request.method()}));
  const started=performance.now();await page.goto(url);await page.locator('.product-card').first().waitFor();const initialMs=Math.round(performance.now()-started);
  assert.equal(await page.locator('.product-card').count(),40);assert.equal(await page.locator('#result-count').textContent(),'48');assert.equal(await page.locator('.brand-option').count(),25);
  assert.equal(await page.locator('#page-title').textContent(),'SHOES TRENDS');assert.equal(await page.locator('.intro-copy').count(),0);
  assert.equal(await page.locator('#keyword-list button').count(),21,'Entire keyword directory must remain visible, including zero matches');
  assert.equal(await page.locator('.keyword-name').evaluateAll(nodes=>nodes.every(n=>!/\p{Script=Hangul}/u.test(n.textContent))),true,'Keyword labels must be English');
  assert.equal(await page.locator('.keyword .rank.unranked').count(),20,'No fabricated rank for themes awaiting evidence');
  await page.getByRole('button',{name:'SNS',exact:true}).click();await page.locator('[data-brand="On"]').check();await page.locator('#category-filter').selectOption('sandal');await page.locator('#fit-filter').selectOption('DISCOVERY');await page.locator('#release-filter').selectOption('upcoming');await page.locator('#search').fill('nonmatching');
  await page.getByRole('button',{name:'Retro Runners 관련 상품 49개',exact:true}).click();await page.waitForTimeout(150);
  assert.equal(await page.locator('#result-count').textContent(),'49','Keyword includes attribute-only matches and upcoming, but never expired/unknown dates');
  assert.equal(await page.locator('.product-card').count(),40);assert.equal(await page.locator('#search').inputValue(),'');assert.equal(await page.locator('#fit-filter').inputValue(),'all');assert.equal(await page.locator('#category-filter').inputValue(),'all');assert.equal(await page.locator('#release-filter').inputValue(),'all');assert.equal(await page.locator('.brand-option input:checked').count(),0);assert.equal(await page.locator('[data-source="all"]').getAttribute('aria-pressed'),'true');
  await page.getByRole('button',{name:'2페이지',exact:true}).click();assert.equal(await page.locator('.product-card').count(),9,'All keyword matches remain reachable through pagination');
  await page.getByRole('button',{name:'필터 초기화',exact:true}).first().click();
  await page.locator('#release-filter').selectOption('upcoming');assert.equal(await page.locator('.product-card').count(),1);assert.equal(await page.locator('.release-badge').textContent(),'발매 예정');await page.locator('#release-filter').selectOption('released');
  await page.screenshot({path:path.join(out,'desktop.png'),fullPage:false});
  await page.getByRole('button',{name:'SNS',exact:true}).click();await page.getByText('SNS 인기 기준을 충족한 상품이 없습니다',{exact:true}).waitFor();
  assert((await page.locator('#result-description').textContent()).includes('확인된 원문 출처가 아직 없습니다.'));
  assert((await page.locator('#result-description').textContent()).includes('확인 대상: Instagram 공개 원문'));assert((await page.locator('#result-description').textContent()).includes('현재 인기 기준을 충족한 게시물은 없습니다.'));assert.equal(await page.locator('#result-description a').getAttribute('href'),'https://www.instagram.com/');
  await page.getByRole('button',{name:'이커머스 랭킹',exact:true}).click();assert.equal(await page.locator('#result-description a').textContent(),'Verified Commerce ↗','Only the actual observed ecommerce platform is named');
  await page.getByRole('button',{name:'뉴스레터',exact:true}).click();assert((await page.locator('#result-description').textContent()).includes('수집 대상 (원문 확인 전)'));assert.equal(await page.locator('#result-description a').textContent(),'Planned Newsletter ↗');
  await page.getByRole('button',{name:'매거진',exact:true}).click();assert.equal(await page.locator('.product-card').count(),1);assert((await page.locator('#result-description').textContent()).includes('카탈로그 원문 출처: Verified Editorial'));assert.equal(await page.locator('#result-description a').first().getAttribute('href'),'https://example.org/');assert((await page.locator('.source-context').first().textContent()).includes('Planned Editorial'));
  await page.getByRole('button',{name:'전체',exact:true}).click();
  await page.getByRole('button',{name:'Nike 테스트 Runner 00 상세정보',exact:true}).click();
  await page.getByRole('heading',{name:'테스트 Runner 00',exact:true}).waitFor();assert((await page.locator('.detail-data').textContent()).includes('US'));assert.equal(await page.getByRole('link',{name:'공식 상품 보기 ↗',exact:true}).getAttribute('href'),'https://example.org/product/0');assert.equal(await page.locator('.ranking-context').textContent(),'집계 기간: 최근 1주 · BEST 목록의 표시 순위');
  await page.getByRole('button',{name:'상품 선택',exact:true}).click();await page.getByRole('button',{name:'상세정보 닫기',exact:true}).click();
  await page.getByRole('button',{name:'2페이지',exact:true}).click();assert.equal(await page.locator('.product-card').count(),8);
  await page.locator('[data-select="p40"]').check();assert.equal(await page.locator('#selection-count').textContent(),'2개 선택');
  await page.getByRole('button',{name:/선택 정보 다운로드/}).click();await page.getByRole('button',{name:'전체 해제',exact:true}).click();
  await page.getByRole('button',{name:'CSV 다운로드',exact:true}).click();assert((await page.locator('#export-error').textContent()).includes('하나 이상'));
  await page.locator('#export-columns input[value="brand"]').check();await page.locator('#export-columns input[value="product_name"]').check();
  const csvWait=page.waitForEvent('download');await page.getByRole('button',{name:'CSV 다운로드',exact:true}).click();const csv=await csvWait;const csvPath=path.join(out,csv.suggestedFilename());await csv.saveAs(csvPath);const text=await fs.readFile(csvPath,'utf8');assert(text.includes('"brand","product_name"'));assert.equal(text.trim().split('\r\n').length,3);assert(!text.includes('fit'));assert(text.includes('Runner 40'));
  await page.getByRole('button',{name:/선택 정보 다운로드/}).click();const xlsxWait=page.waitForEvent('download');await page.getByRole('button',{name:'Excel 다운로드',exact:true}).click();const xlsx=await xlsxWait;const xlsxPath=path.join(out,xlsx.suggestedFilename());await xlsx.saveAs(xlsxPath);assert.equal((await fs.readFile(xlsxPath)).subarray(0,2).toString(),'PK');
  await page.locator('#search').fill('트레일');await page.waitForTimeout(150);assert.equal(await page.locator('.product-card').count(),2);
  await page.locator('#fit-filter').selectOption('common');assert.equal(await page.locator('.product-card').count(),1);
  await page.getByRole('button',{name:'필터 초기화',exact:true}).first().click();
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{window.scrollTo(0,0);document.activeElement?.blur();});await page.screenshot({path:path.join(out,'mobile.png'),fullPage:false});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,'Mobile must not overflow horizontally');
  await page.getByRole('button',{name:'브랜드',exact:true}).click();assert.equal(await page.locator('.sidebar').isVisible(),true);await page.locator('#brand-search').fill('Onitsuka');assert.equal(await page.locator('.brand-option').count(),1);await page.locator('[data-brand="Onitsuka Tiger"]').check();assert.equal(await page.locator('#result-count').textContent(),'0');
  assert.equal(requests.filter(r=>r.method!=='GET').length,0,'Visitor never mutates or starts collection');assert.equal(requests.filter(r=>r.url.endsWith('/data/catalog.json')).length,1);assert.equal(errors.length,0,errors.join('\n'));
  await context.route('**/data/catalog.json',r=>r.fulfill({contentType:'application/json',body:'{"schemaVersion":0}'}));await page.goto(url);await page.getByText('게시된 정보를 불러오지 못했습니다',{exact:true}).waitFor();assert.equal(await page.locator('.product-card').count(),0);assert.equal(await page.getByRole('button',{name:'다시 불러오기',exact:true}).isVisible(),true);
  console.log(JSON.stringify({passed:true,initialFixtureRenderMs:initialMs,browserErrors:errors,downloads:[csvPath,xlsxPath],screenshots:[path.join(out,'desktop.png'),path.join(out,'mobile.png')],catalogRequests:1},null,2));
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}
