// Actual catalog smoke test. No fixture products, no Sheet writes, no collection.
import {chromium} from 'playwright';import {createServer} from 'node:http';import fs from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
import {groupProductVariants,releaseState,kstToday} from '../public/assets/catalog-view.mjs';
const root=path.resolve('public'),out=path.resolve('logs/research/preview-oct6');await fs.mkdir(out,{recursive:true});const c=JSON.parse(await fs.readFile(path.join(root,'data/catalog.json'),'utf8'));
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://local').pathname,p=path.resolve(root,'.'+(pathname==='/'?'/index.html':pathname));if(!p.startsWith(root+path.sep))return res.writeHead(403).end();const type={'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.json':'application/json'}[path.extname(p)];res.writeHead(200,{'Content-Type':type||'application/octet-stream'}).end(await fs.readFile(p));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser;try{browser=await chromium.launch({headless:true,...(process.env.UI_BROWSER_CHANNEL?{channel:process.env.UI_BROWSER_CHANNEL}:{})});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.UI_URL||`http://127.0.0.1:${server.address().port}/`);await page.locator('.product-card').first().waitFor();
assert.deepEqual(await page.locator('.brand-group-label').allTextContents(),['LUX','SPORTS']);assert.equal(await page.locator('#brand-list [data-brand]').count(),c.brands.length);assert.equal(await page.locator('.brand-group[aria-label=SPORTS] [data-brand="Cecilie Bahnsen"]').count(),1);assert.equal(await page.locator('.brand-group[aria-label=LUX] [data-brand="Louis Vuitton"]').count(),1);assert.equal(await page.locator('.keyword-help').count(),0);const groups=groupProductVariants(c.products);assert.equal(Number(await page.locator('#result-count').textContent()),groups.length);assert(c.products.every(p=>p.category==='sneaker'&&releaseState(p,kstToday())==='released'));assert.equal(await page.locator('#keyword-list .keyword-select').count(),c.styleTrendKeywords.items.length);assert.equal(await page.locator('#keyword-list a,#style-status a').count(),0);assert.equal(await page.locator('#keyword-list .trend-row').count(),c.styleTrendKeywords.items.length);assert.equal(await page.locator('#keyword-total').textContent(),`${c.styleTrendKeywords.items.length} KEYWORDS`);assert.equal(await page.locator('#keyword-list .keyword-originals').count(),0);
for(const card of await page.locator('.product-card').all()){await card.scrollIntoViewIfNeeded();await card.locator('.card-open img').evaluate(i=>i.decode());}await page.waitForFunction(()=>[...document.querySelectorAll('.card-open img')].every(i=>i.complete),{},{timeout:30000});const bad=await page.locator('.image-missing').count();if(bad)console.log('Missing images',await page.locator('.product-card').filter({has:page.locator('.image-missing')}).evaluateAll(cards=>cards.map(c=>c.dataset.id)));assert.equal(bad,0,'All representative official photos load');for(const brand of ['Miu Miu','Moncler','Cecilie Bahnsen','Celine']){const card=page.locator('.product-card').filter({has:page.locator('.card-brand',{hasText:brand})}).first();await card.screenshot({path:path.join(out,brand.replaceAll(' ','-')+'.png')});}await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'desktop-viewport.png')});await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});await page.locator('.trends').screenshot({path:path.join(out,'keyword-board.png')});
const health=[];for(const group of groups.filter(g=>g.length>1)){const first=group[0];await page.locator(`[data-detail="${first.id}"]`).first().click();for(const p of group){await page.locator(`#detail-content [data-variant="${p.id}"]`).click();await page.locator('.detail-visual img').waitFor();await page.waitForFunction(()=>{const i=document.querySelector('.detail-visual img');return i?.complete&&i.naturalWidth>0;},{},{timeout:20000});health.push(p.id);}await page.getByRole('button',{name:'상세정보 닫기',exact:true}).click();}
for(let i=0;i<c.styleTrendKeywords.items.length;i++){const k=c.styleTrendKeywords.items[i];await page.locator('#keyword-list .keyword-select').nth(i).click();assert.equal(Number(await page.locator('#result-count').textContent()),groupProductVariants(c.products.filter(p=>k.productIds.includes(p.id))).length);}
await page.getByRole('button',{name:'필터 초기화',exact:true}).first().click();await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(out,'mobile.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({passed:true,url:process.env.UI_URL||'local',variants:c.products.length,cards:groups.length,keywords:c.styleTrendKeywords.items.length,switchedPhotos:health.length,images:groups.length,browser:process.env.UI_BROWSER_CHANNEL||'chromium',out},null,2));
}finally{await browser?.close();await new Promise(r=>server.close(r));}
