import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const root=new URL('../',import.meta.url);
const file=new URL('public/index.html',root);
let html=(await fs.readFile(file,'utf8')).replace(/\r\n/g,'\n');
const additions=JSON.parse(await fs.readFile(new URL('data/catalog-2026-09-23.json',root),'utf8'));
const audit=JSON.parse(await fs.readFile(new URL('data/catalog-audit-2026-09-23.json',root),'utf8'));
function valueSpan(src,marker){const start=src.indexOf(marker)+marker.length;assert(start>=marker.length);let depth=0,quoted=false,escaped=false;for(let i=start;i<src.length;i++){const c=src[i];if(quoted){if(escaped)escaped=false;else if(c==='\\')escaped=true;else if(c==='"')quoted=false;}else if(c==='"')quoted=true;else if(c==='[')depth++;else if(c===']'&&--depth===0)return [start,i+1];}throw Error('Unclosed seed');}
const span=valueSpan(html,'const SEED_PRODUCTS=');
const existing=JSON.parse(html.slice(...span));
const ids=new Set(existing.map(p=>p.id));
const byId=new Map(additions.map(p=>[p.id,p]));
const merged=[...existing.map(p=>byId.get(p.id)||p),...additions.filter(p=>!ids.has(p.id))];
assert.equal(new Set(merged.map(p=>p.id)).size,merged.length,'Duplicate product IDs');
html=html.slice(0,span[0])+JSON.stringify(merged)+html.slice(span[1]);
function replaceOnce(before,after){if(html.includes(after))return;assert(html.includes(before),'Missing expected code: '+before.slice(0,80));html=html.replace(before,after);}
replaceOnce("let LIVE_PRODUCTS=safeParse(APP_STORAGE.getItem(LIVE_KEY),SEED_PRODUCTS)","let LIVE_PRODUCTS=safeParse(APP_STORAGE.getItem(LIVE_KEY),[])");
replaceOnce("META=safeParse(APP_STORAGE.getItem(META_KEY),{})",`META=safeParse(APP_STORAGE.getItem(META_KEY),{lastUpdateDay:'2026-09-23',lastFinished:'2026-09-23 KST',lastNewItems:${audit.addedRecords}})`);
replaceOnce("const APP_STORAGE=(()=>{try{const s=window.localStorage,k='__mlb_shoes_storage_test__';s.setItem(k,'1');s.removeItem(k);return s}catch(e){const mem=new Map();return {getItem:k=>mem.has(k)?mem.get(k):null,setItem:(k,v)=>mem.set(k,String(v)),removeItem:k=>mem.delete(k)}}})();", "const APP_STORAGE=(()=>{const mem=new Map();let storage;try{storage=window.localStorage}catch{}return {getItem:k=>{if(mem.has(k))return mem.get(k);try{return storage?.getItem(k)??null}catch{return null}},setItem:(k,v)=>{v=String(v);try{if(!storage)throw Error('Storage unavailable');storage.setItem(k,v);mem.delete(k)}catch{mem.set(k,v)}},removeItem:k=>{mem.delete(k);try{storage?.removeItem(k)}catch{}}}})();");
replaceOnce("function cleanRecord(p){return !!(p&&isShoeRecord(p)&&productQualityGate(p)&&ssSeasonEligible(p)&&!banned(p))}",`function isVerifiedCatalogRecord(p){return p?.catalogVerification==='official-catalog-2026-09-23'&&p.productType==='sneaker'&&['new-arrival','newest','announcement'].includes(p.sourceEvidence?.kind)&&/^https:\\/\\//.test(p.sourceEvidence?.url||'')&&p.imageValidation?.status==='verified'&&p.imageValidation.width>=120&&p.imageValidation.height>=100}
function cleanRecord(p){return !!(p&&isShoeRecord(p)&&productQualityGate(p)&&(isVerifiedCatalogRecord(p)||ssSeasonEligible(p))&&!banned(p))}`);
replaceOnce("function banned(p){\n  const h=", "function banned(p){\n  if(isVerifiedCatalogRecord(p))return false;\n  const h=");
replaceOnce("function tierLabel(p){if(p.evidence===", "function tierLabel(p){if(isVerifiedCatalogRecord(p)){if(p.status==='upcoming')return '공식 발매 예정';return p.sourceEvidence.kind==='newest'?'공식 최신순 · 09/23':'공식 NEW · 09/23'}if(p.evidence===");
replaceOnce("$('#headerLastUpdate').textContent=`내장 스냅샷 · ${TREND_DATA?.updated||TREND_SNAPSHOT.updated}`", "$('#headerLastUpdate').textContent=`상품 확인 · 2026-09-23`");
replaceOnce("const official=all.filter(p=>p.evidence==='official_latest'||p.evidence==='live_official'||p.evidence==='manual_official');", "const official=all.filter(p=>isVerifiedCatalogRecord(p)||p.evidence==='official_latest'||p.evidence==='live_official'||p.evidence==='manual_official');");
replaceOnce("try{initResearchStrictCounts();render();scheduleDaily()}",`try{initResearchStrictCounts();render();setProgress(false);$('#updateTitle').textContent='공식 상품 반영 · 2026-09-23';$('#updateNote').textContent='공식 근거가 확인된 ${audit.brandsWithAdditions}개 브랜드의 스니커즈 ${audit.addedRecords}개를 추가했습니다. 전체 브랜드의 확인 범위는 페이지 하단의 현황표에서 확인할 수 있습니다.';scheduleDaily()}`);
html=html.replace(/shoes-ss-(live-products|seen|trend|meta)-v19/g,'shoes-ss-$1-pub-20260923');
// Static cards may finish loading before the bottom-of-page script initializes.
html=html.replaceAll('onerror="handleProductImageError(this)"','onerror="window.handleProductImageError?.(this)"').replaceAll('onload="handleProductImageLoad(this)"','onload="window.handleProductImageLoad?.(this)"');
html=html.replace(/<p class="footer-note">[\s\S]*?<\/p><\/footer>/,`<p class="footer-note">2026-09-23 공식 상품 확인: ${audit.brandsWithAdditions}개 브랜드 · ${audit.addedRecords}개 추가 · 발매 예정 ${audit.upcomingRecords}개. 기준 기간은 2026-06-23~2026-09-23이며, 발매일 미확인 상품은 공식 NEW ARRIVAL 또는 최신순 상위 노출을 근거로 수록했습니다. 이번 검증 스니커즈에는 가을·겨울 상품도 포함합니다. 요청된 116개 브랜드 전체의 수집 완료를 의미하지 않습니다. <a href="./catalog-coverage.html">브랜드별 확인 범위 및 미확인 항목 보기 ↗</a></p></footer>`);
if(!html.includes('id="catalogUpdateNotice"'))html=html.replace('<main',`<div id="catalogUpdateNotice" style="padding:12px 24px;background:#f1f5f0;border-bottom:1px solid #dce5d8;font-size:13px;line-height:1.6">2026.09.23 업데이트 · 공식 검증 <strong>${audit.addedRecords}개 추가</strong> · 발매 예정 포함 · 발매일 미확인은 NEW ARRIVAL/최신순 근거 표시 · <a href="./catalog-coverage.html">116개 브랜드 확인 현황</a></div><main`);
await fs.writeFile(file,html);
await fs.writeFile(new URL('data/last_update.json',root),JSON.stringify({updated_at:'2026-09-23',product_count:merged.length,mandatory_brand_count:116,new_items:additions.length,brands_with_additions:audit.brandsWithAdditions,upcoming_items:audit.upcomingRecords,complete:false,coverage_report:'catalog-audit-2026-09-23.json'},null,2));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const rows=audit.coverage.map(b=>`<tr><td>${esc(b.requestedName)}</td><td>${b.added}</td><td>${b.added?'확인 상품 반영 · 전체 범위 미확인':'추가 확인 필요'}</td><td>${b.sourceUrls.slice(0,5).map((u,i)=>`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">공식 출처 ${i+1}</a>`).join(' · ')}</td></tr>`).join('');
await fs.writeFile(new URL('public/catalog-coverage.html',root),`<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>브랜드별 상품 확인 현황</title><style>body{font:15px/1.65 system-ui,sans-serif;margin:32px auto;padding:0 20px;max-width:1100px;color:#20241f}a{color:#306241}h1{font-size:27px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid #ddd;padding:12px 8px;text-align:left}th{background:#f1f5f0;position:sticky;top:0}.note{padding:18px;background:#f1f5f0}td:nth-child(2){font-variant-numeric:tabular-nums}</style><a href="./">← 상품 대시보드</a><h1>116개 브랜드 상품 확인 현황</h1><p>2026-09-23 기준 · 기존 ${audit.existingRecords}개 유지 · ${audit.brandsWithAdditions}개 브랜드에서 ${audit.addedRecords}개 추가 · 발매 예정 ${audit.upcomingRecords}개</p><div class="note">확정 발매일 기준: 2026-06-23~2026-09-23. 발매 예정 제품도 포함합니다. 발매일이 없는 상품은 공식 NEW ARRIVAL 또는 최신순 첫 페이지에서 확인한 스니커즈입니다. 확인일과 쇼핑몰 등록일을 발매일로 사용하지 않았습니다.<br>모든 브랜드·지역·페이지의 전체 상품 수집은 완료되지 않았습니다. ‘추가 확인 필요’는 신상품이 없다는 뜻이 아닙니다. 접근 제한이나 신상품 근거 부족으로 이번 추가 목록에 넣지 못한 브랜드도 포함됩니다. 공식 SKU와 상품 주소가 같은 후보는 중복으로 제외했습니다. 색상별 상품은 별도 항목일 수 있습니다.</div><p><a href="./data/catalog-audit-2026-09-23.json">상세 확인 기록(JSON)</a></p><table><thead><tr><th>브랜드</th><th>추가 수</th><th>확인 상태</th><th>출처</th></tr></thead><tbody>${rows}</tbody></table></html>`);
console.log(JSON.stringify({previous:existing.length,total:merged.length,addedNow:merged.length-existing.length}));
